#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/rcon-by-vincent:latest
    restart: on-failure:5
    environment:
      - PORT=3000
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - RCON_HOST=${RCON_HOST}
      - RCON_PASSWORD=${RCON_PASSWORD}
    ports:
      - "3007:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3007/"]
      interval: 30s
      timeout: 10s
      retries: 5
